name: Lint Models On Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  checks: write

env:
  DBT_PROFILES_DIR: ./

jobs:
  lint-models:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache Python
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-dbt-${{ hashFiles('**/packages.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install SQLFluff
        run: "pip install sqlfluff"

      - name: Get changed SQL files in the models directory or its subdirectories
        id: get_file_changes
        uses: tj-actions/changed-files@v44
        with:
          files: 'models/**/*.sql'

      - name: Lint dbt models
        id: sqlfluff_json
        env:
          LINTEES: ${{ steps.get_file_changes.outputs.all_changed_files }}
        if: ${{ steps.get_file_changes.outputs.all_changed_files }} != ''
        shell: bash -l {0}
        run: sqlfluff lint --format github-annotation --annotation-level failure --nofail ${{ steps.get_file_changes.outputs.all_changed_files }} > annotations.json

      - name: Annotate
        uses: yuzutech/annotations-action@v0.5.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"